---
# tasks file for nginx operator

- name: Create the Operator Deployment
  k8s:
    state: present
    definition: "{{lookup('template', 'deployment.yml') | from_yaml}}"

- name: Create the Operator Service
  k8s:
    state: present
    definition: "{{lookup('template', 'service.yml') | from_yaml}}"

#- name: Create the Operator Route
#  k8s:
#    state: present
#    definition: "{{lookup('template', 'route.yml') | from_yaml}}"