apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ ansible_operator_meta.namespace }}
  labels: 
    app.kubernetes.io/name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx